name: Test KICS action

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/actions/kics-github-action/**"
      - ".github/workflows/test-kics.yaml"
  push:
    paths:
      - ".github/actions/kics-github-action/**"
      - ".github/workflows/test-kics.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: mkdir -p myoutput
      - name: Test KICS action
        uses: ./.github/actions/kics-github-action
        with:
          path: .github/actions/kics-github-action/test/samples/positive1.tf,.github/actions/kics-github-action/test/samples/positive2.tf
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: "60"
          output_path: myoutput/
          output_formats: sarif
          ignore_on_exit: results
          enable_comments: true
          enable_annotations: true
          enable_jobs_summary: true
          comments_with_queries: true
          excluded_column_for_comments_with_queries: "description_id,similarity_id,search_line,search_value,cis_description_id,cis_description_title,cis_description_text,cloud_provider"
      - run: ls -la && ls -la myoutput
        if: always()
